all:
  children:
    production:
      hosts: 51.195.100.108
      vars:
        ansible_network_os: cisco.ios.ios
        ansible_python_interpreter: /usr/bin/python3

  vars:
    root_dir: "/home/{{ ansible_user }}/warehouse"