---

- name: Create a root app directory
  ansible.builtin.file:
    path: "{{ root_dir }}"
    state: directory
    recurse: yes
    mode: "0755"
  tags:
    - clone

- name: Clone source code from github repo
  git: 
    repo: https://github.com/flanar/warehouse.git
    dest: '{{ root_dir }}'
    force: yes
    version: '{{ next_app_version }}'
  tags:
    - clone

- name: Install NPM packages
  become: yes
  community.general.npm:
    name: "{{ package['name'] }}"
    global: "{{ package['is_global'] }}"
  loop_control:
    loop_var: package
  with_items:
    - "{{ npm_packages }}"

- name: Install web dependencies
  shell: yarn install
  args:
    chdir: '{{ root_dir }}'
  tags:
    - install-web-dependencies

- name: Build css
  shell: yarn build:style
  args:
    chdir: '{{ root_dir }}'
  tags:
    - build-web-services

- name: Build web services
  shell: yarn build
  args:
    chdir: '{{ root_dir }}'
  tags:
    - build-web-services

- name: Make migrations
  shell: yarn migrate
  args:
    chdir: '{{ root_dir }}'
  tags:
    - database

- name: Seed database
  shell: yarn seed
  args:
    chdir: '{{ root_dir }}'
  tags:
    - database

- name: Copy PM2 `ecosystem` configuration file
  ansible.builtin.copy:
    src: "{{ role_path }}/files//{{ ecosystem_file }}"
    dest: "{{ root_dir }}/{{ ecosystem_file }}"
  tags:
    - run

- name: Copy run script
  ansible.builtin.copy:
    src: "{{ role_path }}/files//run"
    dest: "{{ root_dir }}/run"
    mode: a+x
  tags:
    - run

- name: Start a PM2 manager
  ansible.builtin.shell: "./run"
  args:
    chdir: "{{ root_dir }}"
  tags:
    - run
